export const SET_USER: string = 'SET_USER'
export const SET_SECTIONS: string = 'SET_SECTION'
export const SET_PRODUCTS: string = 'SET_PRODUCT'
export const RESET_PRODUCTS: string = 'RESET_PRODUCT'
export const SET_CART: string = 'SET_CART'
export const RESET_CART: string = 'RESET_CART'
export const EDIT_CART: string = 'EDIT_CART'
export const DEL_FROM_CART: string = 'DEL_FROM_CART'